### PR TITLE
got itineraries to save

### PR DESCRIPTION
**Pull request by kristen-howton**
### What I did:
- Moved the order of the arguments in itinerary list to get it to display the names of parks, businesses, and attractions
- Added id's in json to see if it would display on page

### What to do to check:
- See if the information is displaying on your page
- You can add dummy information for other id information to see if it also works

### CODE REVIEW

**Review by JaysonRice — APPROVED** [review]
The saved itineraries are on the DOM! You are a lifesaver!

**Comment by Hellowalls1** [comment]
Looks good!

**Review by Hellowalls1 — APPROVED** [review]

**Comment by TylerSerafin** [comment]
Looks good!

**Review by TylerSerafin — APPROVED** [review]

**Review by slochowsky — APPROVED** [review]
yahssssss

**Pull request merged**
