### PR TITLE
Parks dialog functional

### PR DESCRIPTION
**Pull request by kristen-howton**
### What Happened:
- Updated park.js to include logic to include overview and amenities logic
- Updated park.js to include a "close dialog" button
- Wrote the logic for the "click" event
- Moved image to inside of dialog box

### Would you please....
- Pull down the code
- Make sure the code looks makes sense in terms of functionality and formatting
- Serve the page and make sure that the details button has the proper functionality
- Make sure you see the image

### CODE REVIEW

**Review by slochowsky — APPROVED** [review]
bingo

**Review by JaysonRice — APPROVED** [review]
Parks look good!

**Comment by TylerSerafin** [comment]
you're a winner!

**Comment by Hellowalls1** [comment]
U dun gud.

**Review by TylerSerafin — APPROVED** [review]

**Review by Hellowalls1 — APPROVED** [review]

**Pull request merged**
