### PR TITLE
Ts api

### PR DESCRIPTION
**Pull request by TylerSerafin**
### Changes made:
- Added the park dropdown menu
- Added 50 park selections
- Setup a custom event

### Things to check:
1. Make sure the dropdown renders to the dom
2. Make sure all park selections show up

### CODE REVIEW

**Comment by slochowsky** [comment]
LoOkS GoOd ShiP iT

**Review by JaysonRice — APPROVED** [review]
The dropdown works!

**Review by kristen-howton — APPROVED** [review]
IT IS PERFECT!!

**Comment by Hellowalls1** [comment]
LOOKS GREAT!

**Pull request merged**
