### PR TITLE
EateryCard Dialog

### PR DESCRIPTION
**Pull request by TylerSerafin**
### Changes made
- Created dialog boxes for Eateries
- Added cities and states to Eatery.js

### Things to check
- Make sure dialog boxes show up under eatery cards
- Make sure cities and states show up for Eatery locations

### CODE REVIEW

**Review by kristen-howton — APPROVED** [review]
🥇 Works on my machine, ship it!!

**Comment by slochowsky** [comment]
Id buy this app

**Review by JaysonRice — APPROVED** [review]
The dialog box for the eateries works! wow!

**Review by Hellowalls1 — APPROVED** [review]
Tyler. You did a fantastic job with your team. 

A long long time ago,

In a galaxy far far away.....

**Pull request merged**
