### PR TITLE
Saving Itinerary

### PR DESCRIPTION
**Pull request by slochowsky**
**WHAT I DID**
Enabled the saved Itinerary button to post selected data to API.

**WHAT TO CHECK**
Cycle through a few itinerary options and make sure multiple itinerary's can be saved, also
check all other application features.

### CODE REVIEW

**Review by JaysonRice — APPROVED** [review]
The save button saves data to the JSON server with the dropdown values!!!

**Review by kristen-howton — APPROVED** [review]
🥇 You did the things, way to go!!!

**Review by TylerSerafin — APPROVED** [review]
itineraries save! Looks good

**Review by Hellowalls1 — APPROVED** [review]
Looks so good blake. Go team.

**Pull request merged**
