### PR TITLE
Setup Itinerary provider, list and HTML

### PR DESCRIPTION
**Pull request by TylerSerafin**
### Changes made
These changes are made inside the ItineraryList, Itinerary.js and Itineraries.json.
- Setup a provider for Itinerary
- Setup a list for Itinerary
- Setup HTML for Itinerary

### Things to check
- Nothing is displayed on the page yet, so please make sure code follows what we've been doing.

### CODE REVIEW

**Comment by Hellowalls1** [comment]
Pulled down. Looks like it has the things we need to do the thing.

**Review by Hellowalls1 — APPROVED** [review]

**Review by JaysonRice — APPROVED** [review]
This logic will help us succeed

**Review by kristen-howton — APPROVED** [review]
🥇 Lets ship it and set up the the itinerary preview!!

**Comment by slochowsky** [comment]
- -
 -

**Pull request merged**
