### PR TITLE
used .sort or sort alphabetical order with states beside park name

### PR DESCRIPTION
**Pull request by slochowsky**
sorted all dropdowns in alphabetical orderby state

### CODE REVIEW

**Review by JaysonRice — APPROVED** [review]
The dropdowns are sorted by state! Looks good.

**Comment by TylerSerafin** [comment]
Looks good!

**Comment by Hellowalls1** [comment]
The dropdowns are sorting in alphabetical order which is really neat. Thanks for your contribution. Looking forward to working with you in the future.

**Review by kristen-howton — APPROVED** [review]
Looks great!! Just make pull requests that tell us what to do to check.

**Pull request merged**
