### PR TITLE
Park Dropdown

### PR DESCRIPTION
**Pull request by Hellowalls1**
What happened:

-Got the Park dropdown to populate a card below the weather with a selected option and detail button

What We Need From You:

-Pull down the code
-Examine the code to make sure it look good
-Check to make sure that selecting a park in the Park dropdown populates the park card below

### CODE REVIEW

**Review by JaysonRice — APPROVED** [review]
Park cards populate from the park dropdown. 👍

**Comment by slochowsky** [comment]
perfect

**Comment by TylerSerafin** [comment]
Looks good!

**Review by kristen-howton — APPROVED** [review]
🥇 SHIP IT!!

**Review by TylerSerafin — APPROVED** [review]

**Pull request merged**
